version: '3'
services:
  api:
    build: .
    ports: 
      - 8000:8000
    environment:
      - DATABASE_HOSTNAME=postgres
      - DATABASE_PORT=5432
      - DATABASE_PASSWORD=Judithida1
      - database_name=africatradetoday
      - DATABASE_USERNAME=postgres
      - SECRET_KEY=09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
      - ALGORITHM=HS256
      - access_token_expire_minutes=30
      
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=AfricaTradeToday1
      - POSTGRES_DB=africatradetoday

    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db: